Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,8 +40,9 @@ jobs:
           mkdir -p org-repos
           cd org-repos
           for org in $(gh api user/orgs --jq '.[].login'); do
-            for repo in $(gh repo list $org --limit 100 --json name -q '.[].name'); do
-              git submodule add https://$GITHUB_TOKEN@github.com/$org/$repo.git $org/$repo
+            for repo in $(gh repo list $org --limit 100 --json name,defaultBranchRef -q '.[] | select(.defaultBranchRef != null) | .name'); do
+              echo "Cloning $org/$repo"
+              git submodule add https://$GITHUB_TOKEN@github.com/$org/$repo.git $org/$repo || echo "Failed to add $org/$repo as a submodule"
             done
           done
         env:
