Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,8 +41,13 @@ jobs:
           cd org-repos
           for org in $(gh api user/orgs --jq '.[].login'); do
             for repo in $(gh repo list $org --limit 100 --json name,defaultBranchRef -q '.[] | select(.defaultBranchRef != null) | .name'); do
-              echo "Cloning $org/$repo"
-              git submodule add https://$GITHUB_TOKEN@github.com/$org/$repo.git $org/$repo || echo "Failed to add $org/$repo as a submodule"
+              echo "Checking $org/$repo"
+              if [ "$(gh api repos/$org/$repo/branches --jq '.[] | select(.protected == false) | .name')" ]; then
+                echo "Cloning $org/$repo"
+                git submodule add https://$GITHUB_TOKEN@github.com/$org/$repo.git $org/$repo || echo "Failed to add $org/$repo as a submodule"
+              else
+                echo "Skipping $org/$repo (no unprotected branches or empty repository)"
+              fi
             done
           done
         env:
